### ISSUE TITLE
WolfoAlternateSkins Unlocks

### ISSUE THREAD

**Issue by zechsmachine** [WolfoIsBestWolf/ror2-LittleGameplayTweaks#2]
Kindly requesting skins not all be bound to the same unlock condition. It removes any incentive to do less favored content like Twisted Scavenger at all if you can simply play Simulacrum or go to Voidling and achieve the same result.

Sorry if this is the wrong repo for this as well, but I couldn't find one up for AlternateSkins and the mod's description says it's an extension of this.

**Comment by DamageMaximo** [comment]
I disagree, if this is implement hopefully it's as an option, I like unlocking more than one skin for beating voidling.
