### ISSUE TITLE
[Request] Config option to disable stage-bound chest alterations

### ISSUE THREAD

**Issue by khdtheryu** [WolfoIsBestWolf/ror2-LittleGameplayTweaks#3]
Hello! 
I would like to request an option to disable stage-bound chest category alterations, meaning an option to retain vanilla chest category spawn logic. It is quite annoying that sometimes when I drop on Titanic Plains 4 out of 6 chests are healing only. Or on Distant Roost they are 3 out of 6 utility. This spawn pool change ruins a lot of run starts for me. 
Otherwise, great mod and thank you.

**Comment by WolfoIsBestWolf** [comment]
I have removed this feature in the next patch.

Do think vanilla having only 1 type of Large Category chest per stage is weird but yeah, don't think this feature added much.
