### ISSUE TITLE
As of SOTS Engineer is unable to place turrets

### ISSUE THREAD

**Issue by PepperoniPlaya** [WolfoIsBestWolf/ror2-LittleGameplayTweaks#4]
To confirm this issue I made a new mod profile with only this mod installed. Upon attempting to place a turret as engineer it just shows up as a blank minion with an "X" beside it. Hopefully this mod will get updated because it is one of my absolute faves 👍
![engi](https://github.com/user-attachments/assets/1352fdd4-1286-48b0-b756-7756ef842856)

**Comment by WolfoIsBestWolf** [comment]
This is was with a version that wasn't yet compatible with Sots so i'll close it as it's updated now.
