### ISSUE TITLE
Laser scope doesn't give 10 crit anymore :(

### ISSUE THREAD

**Issue by DamageMaximo** [WolfoIsBestWolf/ror2-LittleGameplayTweaks#6]
The title says it all, I have it enabled and it still doesn't do that

**Comment by WolfoIsBestWolf** [comment]
Item buffs have moved into their own mod.
https://thunderstore.io/package/Wolfo/WolfoItemBuffs/

Old config values don't ever get deleted when removed from a mod. Sorry for the inconvenience.
