### ISSUE TITLE
config request

### ISSUE THREAD

**Issue by DamageMaximo** [WolfoIsBestWolf/ror2-LittleGameplayTweaks#7]
Hello, I made this post to request a config to enable/disable:

- "Replaced Lesser Wisp with Jellyfish on Verdant/Viscous Falls"
- Separate the void fields cells' regen from the faster charge as two separate options to keep one and disable the other.

That was a really nice update to the mod, these are just the only things I wish were configurable and I at least have not been able to find a config for these.

EDIT: I've just realized, maybe the first request falls into the "Changes to spawn enemy spawn pools (Pre Loop)" section, is this correct? Sorry I didn't notice this sooner, I haven't slept in 17 hours I'm tired. :)

**Comment by WolfoIsBestWolf** [comment]
I will not make config for specific enemy changes. But stage specific config was something requested before (mostly by SulfurPool haters) I can do that sure.

Else yeah you could disable all Pre-Loop enemy changes.

I can separate the Regen and Timer yeah.
